<a href="https://colab.research.google.com/github/shailza969/Titanic-Survival-Project/blob/main/Titanic_Logisitic_and_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
train_df = pd.read_csv("/content/train.csv")

In [ ]:
train_df.shape

(891, 12)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
l1 = ['PassengerId','Name','Cabin','Ticket' ]
train_df.drop(l1,axis= 1, inplace = True)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
train_df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
train_df['Age'].fillna(train_df['Age'].mean(), inplace= True)
train_df['Embarked'].fillna(str(train_df['Embarked'].mode), inplace= True)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [ ]:
from sklearn.preprocessing import LabelEncoder
le_s = LabelEncoder()
le_e = LabelEncoder()
train_df['Sex']  = le_s.fit_transform(train_df['Sex'])
train_df['Embarked']  = le_e.fit_transform(train_df['Embarked'])

In [ ]:
le_s.classes_, le_e.classes_

(array(['female', 'male'], dtype=object),
 array(['<bound method Series.mode of 0      S\n1      C\n2      S\n3      S\n4      S\n      ..\n886    S\n887    S\n888    S\n889    C\n890    Q\nName: Embarked, Length: 891, dtype: object>',
        'C', 'Q', 'S'], dtype=object))

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [ ]:
train_df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         3
1         1       1    0  38.0      1      0  71.2833         1
2         1       3    0  26.0      0      0   7.9250         3
3         1       1    0  35.0      1      0  53.1000         3
4         0       3    1  35.0      0      0   8.0500         3

In [ ]:
X= train_df.iloc[:, 1:].values
Y = train_df.iloc[:, 0].values

In [ ]:
from sklearn.linear_model import LogisticRegression


In [ ]:
Lgr= LogisticRegression(solver = 'newton-cg', n_jobs =-1 )

In [ ]:
Lgr.fit(X, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
Y_pred = Lgr.predict(X)

In [ ]:
Lgr.score(X, Y)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(Y_pred, Y)

array([[475, 102],
       [ 74, 240]])

In [ ]:
(Y_pred == Y).sum()/Y_pred.shape

array([0.80246914])

# SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
clf = SVC( C=100, decision_function_shape = 'ovr', gamma =1)

In [ ]:
clf.fit(X,Y)                  

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
pred_y1 = clf.predict(X)

In [ ]:
clf.score(X,Y)

0.9708193041526375

In [ ]:
confusion_matrix(pred_y1, Y)

array([[544,  21],
       [  5, 321]])

In [ ]:
confusion_matrix(Y_pred, Y)

array([[475, 102],
       [ 74, 240]])

In [ ]:
(pred_y1 == Y).sum()/pred_y1.shape

array([0.9708193])