<a href="https://colab.research.google.com/github/shailza969/Titanic-datastet-projects/blob/main/Titanic_Logisitic_and_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [52]:
train_df = pd.read_csv("/content/train.csv")
test_df = pd.read_csv("/content/test.csv")

In [53]:
train_df.shape, test_df.shape

((891, 12), (418, 11))

In [54]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [55]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


# Preprocessing

In [56]:
l1 = ['PassengerId','Name','Cabin','Ticket' ]
train_df.drop(l1,axis= 1, inplace = True)
test_df.drop(l1,axis= 1, inplace = True)

In [57]:
print(train_df.info())
print(test_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  418 non

In [58]:
train_df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [59]:
test_df.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [60]:
train_df['Age'].fillna(train_df['Age'].mean(), inplace= True)
test_df['Age'].fillna(train_df['Age'].mean(), inplace= True)
train_df['Embarked'].fillna(str(train_df['Embarked'].mode), inplace= True)
test_df['Fare'].fillna(test_df['Fare'].mean(), inplace= True)

In [61]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [62]:
test_df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [63]:
from sklearn.preprocessing import LabelEncoder
le_s = LabelEncoder()
le_e = LabelEncoder()
train_df['Sex']  = le_s.fit_transform(train_df['Sex'])
train_df['Embarked']  = le_e.fit_transform(train_df['Embarked'])
test_df['Sex']  = le_s.transform(test_df['Sex'])
test_df['Embarked']  = le_e.transform(test_df['Embarked'])

In [64]:
le_s.classes_, le_e.classes_

(array(['female', 'male'], dtype=object),
 array(['<bound method Series.mode of 0      S\n1      C\n2      S\n3      S\n4      S\n      ..\n886    S\n887    S\n888    S\n889    C\n890    Q\nName: Embarked, Length: 891, dtype: object>',
        'C', 'Q', 'S'], dtype=object))

In [65]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [78]:
train_df.head()
test_df.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  34.5      0      0   7.8292         2
1       3    0  47.0      1      0   7.0000         3
2       2    1  62.0      0      0   9.6875         2
3       3    1  27.0      0      0   8.6625         3
4       3    0  22.0      1      1  12.2875         3

In [79]:
X_train= train_df.iloc[:, 1:].values
Y_train = train_df.iloc[:, 0].values
X_test = test_df.iloc[:, :].values

# Logistic Regr. Model fitting

In [80]:
from sklearn.linear_model import LogisticRegression


In [81]:
Lgr= LogisticRegression(solver = 'newton-cg', n_jobs =-1 )

In [82]:
Lgr.fit(X, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [85]:
Y_pred2 = Lgr.predict(X_test)
Y_pred = Lgr.predict(X_train)

In [86]:
Lgr.score(X_train, Y_train)

0.8024691358024691

In [87]:
from sklearn.metrics import confusion_matrix

In [89]:
confusion_matrix(Y_pred, Y_train)

array([[475, 102],
       [ 74, 240]])

# SVM

In [90]:
from sklearn.svm import SVC

In [91]:
clf = SVC( C=100, decision_function_shape = 'ovr', gamma =1)

In [92]:
clf.fit(X,Y)                  

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [93]:
pred_y1 = clf.predict(X)

In [94]:
clf.score(X_train,Y_train)

0.9708193041526375

In [96]:
confusion_matrix(pred_y1, Y_train)

array([[544,  21],
       [  5, 321]])

In [99]:
confusion_matrix(Y_pred, Y_train)

array([[475, 102],
       [ 74, 240]])

# To save result in DF

In [100]:
pred_y1 = pd.DataFrame(pred_y1)

In [ ]:
pred_y1.to_csv('answer')

In [ ]:
pred = pd.read_csv('/content/answer')

In [ ]:
pred.head()

Unnamed: 0  0
0           0  0
1           1  1
2           2  1
3           3  1
4           4  0